hello: hello.o
	ld -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -macosx_version_min 10.12 -lSystem hello.o -o hello

hello.o: hello-mac.asm
	nasm -f macho64 hello-mac.asm -o hello.o

clean:
	rm -f hello.o hello
